# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='falcomx',
            name='shortcode',
            field=models.CharField(default='falcomxdefshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
