# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falcomx',
            name='active',
        ),
    ]
