# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_falcomx_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcomx',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
