# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_falcomx_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='falcomx',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
