# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_falcomx_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falcomx',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
